// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjjQz91nAUI-q-S7mxyYYqbtP7YyBM6uA',
    appId: '1:1088067363701:web:bf23a837c740909985293c',
    messagingSenderId: '1088067363701',
    projectId: 'qrcafe-aa724',
    authDomain: 'qrcafe-aa724.firebaseapp.com',
    storageBucket: 'qrcafe-aa724.appspot.com',
    measurementId: 'G-9J17DQHEYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3KO1LgGxw4VH-ypfJ3gwH67FURc8-nU',
    appId: '1:1088067363701:android:b4f49c52021cb57885293c',
    messagingSenderId: '1088067363701',
    projectId: 'qrcafe-aa724',
    storageBucket: 'qrcafe-aa724.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPgpw_a8mSP3a5m6S3x1QNxN7ODxEiZk',
    appId: '1:1088067363701:ios:77354f7958fc940e85293c',
    messagingSenderId: '1088067363701',
    projectId: 'qrcafe-aa724',
    storageBucket: 'qrcafe-aa724.appspot.com',
    iosClientId: '1088067363701-ckafc1jq573b1jeqvqoeiairo9r676j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYPgpw_a8mSP3a5m6S3x1QNxN7ODxEiZk',
    appId: '1:1088067363701:ios:52f2b183cb90fe6185293c',
    messagingSenderId: '1088067363701',
    projectId: 'qrcafe-aa724',
    storageBucket: 'qrcafe-aa724.appspot.com',
    iosClientId: '1088067363701-v22na462jjdt877bg2q58nbpjr4b7fr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrcafe.RunnerTests',
  );
}
